# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [47]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [48]:
print(np.__version__)
print(np.show_config())

1.23.5
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [49]:
x=np.zeros(10)

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [50]:
print(np.size(x))

10


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [51]:
print(np.info())

 info(object=None, maxwidth=76, output=None, toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``None``, in which case ``sys.stdout`` will be used.
    The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP
   polyval(p, x)
 

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [52]:
x[4]=1

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [53]:
x=np.arange(10,49)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [54]:
print(x[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [55]:
x=np.arange(0,9)
x=np.reshape(x,(3,3))
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [56]:
x=np.array([1,2,0,0,4,0])
print(np.nonzero(x))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [57]:
x=np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [58]:
x=np.random.random((3,3,3))
x

array([[[0.01548142, 0.71075393, 0.77919827],
        [0.47142296, 0.26929192, 0.89835938],
        [0.53934886, 0.16107363, 0.5679455 ]],

       [[0.41400244, 0.18021046, 0.79670937],
        [0.14326901, 0.85837719, 0.7093483 ],
        [0.17997587, 0.93517368, 0.75053697]],

       [[0.0458023 , 0.19775427, 0.41346446],
        [0.74136071, 0.16339771, 0.10074993],
        [0.43927727, 0.33110589, 0.11159067]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [59]:
x=np.random.random((10,10))
print(np.min(x))
print(np.max(x))

0.004049877480498121
0.9958329878223546


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [60]:
x=np.random.random(30)
print(np.mean(x))

0.4449421648319109


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [61]:
x=np.ones((5,5))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [62]:
x=np.zeros((5,5))
x[1:-1,1:-1]=1
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [63]:
x=[1,2,3,4]
x1=np.diag(x,k=-1)
print(x1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [72]:
x=np.zeros((8,8))
x[::2]=1
x

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [66]:
x1=np.unravel_index(100,[6,7,8])
x1

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [73]:
x=x=np.tile(np.array([0,1]),(8,8))
x

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [83]:
x1=np.random.random((5,5))
m1=np.min(x1)
m2=np.max(x1)
for i in range(0,5):
    for j in range(0,5):
        x1[i,j]=(x1[i,j]-m1)/(m2-m1)
print(x1)

[[1.         0.66769225 0.5829814  0.13997731 0.46607456]
 [0.         0.62622039 0.27324339 0.09753355 0.02251425]
 [0.91247182 0.881724   0.06163786 0.57384863 0.78079238]
 [0.46618677 0.91327111 0.47102505 0.83566204 0.34817009]
 [0.34991676 0.73113197 0.1703632  0.65041219 0.42546785]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [84]:
x = np.dtype([("R", np.ubyte, 1),
                  ("G", np.ubyte, 1),
                  ("B", np.ubyte, 1),
                  ("A", np.ubyte, 1)])

C:\Users\dhana\AppData\Local\Temp\ipykernel_15900\3961967025.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x = np.dtype([("R", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [85]:
x=np.dot(np.ones((5,3)),np.ones((3,2)))
x

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [86]:
x = np.arange(15)
x [(3 < x) & (x <= 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [87]:
print(9)
print(10)

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [88]:
print('nan')
print(0)
print("[-2.14748365e+09]")

nan
0
[-2.14748365e+09]


C:\Users\dhana\AppData\Local\Temp\ipykernel_15900\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\dhana\AppData\Local\Temp\ipykernel_15900\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [90]:
x = np.random.uniform(-5,+15,5)
print (np.copysign(np.ceil(np.abs(x)), x))

[11.  9. 11.  9. -2.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [94]:
x1 = np.random.randint(0,10,20)
x1
x2 = np.random.randint(0,10,10)
x2
print(np.intersect1d(x1,x2))

[0 1 3 6 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [96]:
d1=np.seterr('ignore')
d1=np.seterr(**d1)


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [97]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [98]:
dates=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [99]:
A=np.ones(4)
B=np.ones(4)*5
print(np.multiply(np.add(A,B),np.divide(np.multiply(A,-1),2)))

[-3. -3. -3. -3.]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [104]:
x = np.random.uniform(0,10,20)

print (x - x%1)
print (np.floor(x))
print (np.ceil(x)-1)
print (x.astype(int))
print (np.trunc(x))

[9. 8. 7. 5. 2. 0. 6. 9. 2. 1. 8. 1. 1. 1. 6. 8. 5. 6. 2. 2.]
[9. 8. 7. 5. 2. 0. 6. 9. 2. 1. 8. 1. 1. 1. 6. 8. 5. 6. 2. 2.]
[9. 8. 7. 5. 2. 0. 6. 9. 2. 1. 8. 1. 1. 1. 6. 8. 5. 6. 2. 2.]
[9 8 7 5 2 0 6 9 2 1 8 1 1 1 6 8 5 6 2 2]
[9. 8. 7. 5. 2. 0. 6. 9. 2. 1. 8. 1. 1. 1. 6. 8. 5. 6. 2. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
x = np.zeros((5,5))
x += np.arange(5)
print(x)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [106]:
def generator():
    for x in range(10):
        yield x
x = np.fromiter(generator(),dtype=float)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [111]:
x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [112]:
x=np.random.random(10)
print(np.sort(x))

[0.11198523 0.12492637 0.17597811 0.29544277 0.35706044 0.44787087
 0.47980616 0.55883658 0.67878688 0.82010642]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [113]:
x=np.arange(77)
print(np.add.reduce(x))

2926


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [115]:
x1=np.random.randint(0,10,10)
x2=np.random.randint(0,10,10)
print(np.array_equal(x1,x2))

False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [116]:
x = np.ones(10)
x.flags.writeable = False
x[0:3] = 0

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [117]:
x = np.random.random((10,2))
X,Y = x[:,0], x[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.43745898 0.59150503 0.53968995 0.43200482 0.2649143  0.75464396
 0.05922714 0.86050856 0.71218026 0.91675715]
[0.89056343 0.22829687 1.13224886 0.59378555 0.39465901 1.1788841
 1.26692673 1.17849571 0.60731745 1.40839107]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [119]:
x = np.random.random(5)
print(x)
x[x.argmax()] = 0
print(x)

[0.96268224 0.42544948 0.72250767 0.77319243 0.20023412]
[0.         0.42544948 0.72250767 0.77319243 0.20023412]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [121]:
x = np.zeros((5,5), [('x',float),('y',float)])
x['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(x)

[[(0.  , 0.) (0.25, 0.) (0.5 , 0.) (0.75, 0.) (1.  , 0.)]
 [(0.  , 0.) (0.25, 0.) (0.5 , 0.) (0.75, 0.) (1.  , 0.)]
 [(0.  , 0.) (0.25, 0.) (0.5 , 0.) (0.75, 0.) (1.  , 0.)]
 [(0.  , 0.) (0.25, 0.) (0.5 , 0.) (0.75, 0.) (1.  , 0.)]
 [(0.  , 0.) (0.25, 0.) (0.5 , 0.) (0.75, 0.) (1.  , 0.)]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [127]:
X = np.arange(4)
Y = X + 3.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)

[[-0.28571429 -0.22222222 -0.18181818 -0.15384615]
 [-0.4        -0.28571429 -0.22222222 -0.18181818]
 [-0.66666667 -0.4        -0.28571429 -0.22222222]
 [-2.         -0.66666667 -0.4        -0.28571429]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [133]:
for dtype in [np.int8, np.int32, np.int64]:
        print(np.iinfo(dtype).min)
        print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
         print(np.finfo(dtype).min)
         print(np.finfo(dtype).max)
         print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [140]:
np.set_printoptions(nanstr=True)
x = np.zeros((5,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
x = np.arange(10)
vec = np.random.uniform(0,10)
index = (np.abs(x-vec)).argmin()
print(x[index])

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [141]:
x = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ... ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\dhana\AppData\Local\Temp\ipykernel_15900\2893404235.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [142]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)#(.T property is for transpose of the vector matrix)
print(D)

[[0.         0.39705251 0.41247446 ... 0.32597722 0.33563936 0.48971463]
 [0.39705251 0.         0.06437755 ... 0.274461   0.1603025  0.21139437]
 [0.41247446 0.06437755 0.         ... 0.33345401 0.22055785 0.27205907]
 ...
 [0.32597722 0.274461   0.33345401 ... 0.         0.11435172 0.20749239]
 [0.33563936 0.1603025  0.22055785 ... 0.11435172 0.         0.1544312 ]
 [0.48971463 0.21139437 0.27205907 ... 0.20749239 0.1544312  0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [143]:
x = np.arange(5, dtype=np.int32)
x = x.astype(np.float32, copy=False)
print(x)

[0. 1. 2. 3. 4.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [153]:
from io import StringIO 
s = StringIO("""1, 2, 3, 4,5 
                6,  ,  , 7, 8
                 ,  , 9,10,11""")
X = np.genfromtxt(s, delimiter=',', dtype=np.int)
print(x)

[0. 1. 2. 3. 4.]


C:\Users\dhana\AppData\Local\Temp\ipykernel_15900\980967666.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.genfromtxt(s, delimiter=',', dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [155]:
x = np.arange(4).reshape(2,2)
for index, value in np.ndenumerate(x):
    print(index, value)
for index in np.ndindex(x.shape):
    print(index, x[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [158]:
n = 7
p = 14
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),7)
print(Z)

[[7. 7. 0. ... 0. 7. 0.]
 [7. 0. 0. ... 7. 0. 0.]
 [0. 0. 0. ... 7. 7. 7.]
 ...
 [0. 7. 0. ... 0. 0. 0.]
 [0. 0. 7. ... 0. 7. 0.]
 [0. 0. 7. ... 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [159]:
x = np.random.randint(10,20,(3,3))
print(x)
print(x[x[:,1].argsort()])

[[19 13 13]
 [14 14 13]
 [19 11 15]]
[[19 11 15]
 [19 13 13]
 [14 14 13]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [163]:
x = np.random.randint(0,10,(4,4))
print((~x.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [165]:
x = np.random.uniform(0,10,10)
X = 0.5
m = x.flat[np.abs(x - X).argmin()]
print(m)

2.064897158158291


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [166]:
x1 = np.arange(3).reshape(3,1)
x2= np.arange(3).reshape(1,3)
it = np.nditer([x1,x2,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [172]:
x = np.ones(5)
i = np.random.randint(0,len(Z),10)
x += np.bincount(i, minlength=len(Z))
print(x)
np.add.at(x,i,1)
print(Z)

[5. 3. 2. 2. 3.]
[5. 9. 3. 3. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [173]:
X = [1,2,3,4,5,6,7,8,9,10]
I= [1,7,2,8,6,4,11,10,13,3]
F = np.bincount(I,X)
print(F)

[0. 1. 3. ... 7. 0. 9.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [174]:
x = np.random.randint(0,10,(4,4))
sum = x.sum(axis=(-2,-1))
print(sum)

79


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [190]:
D= np.array([0.3, 0.5, 0.2, 0.7, 1., -0.6]) # weights
S = np.array([0, 1, 1, 2, 2, 2])
D_sum = np.bincount(S,  weights=D)
D_counts = np.bincount(S)
D_means = D_sum / D_counts
print(D_means)

[0.3        0.35       0.36666667]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [191]:
x1 = np.random.uniform(0,1,(4,4))
x2= np.random.uniform(0,1,(4,4))
np.diag(np.dot(x1,x2))

array([1.12304058, 0.60715505, 1.36449371, 1.55666356])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [194]:
x= np.array([1,2,3,4,5])
nz = 3
z = np.zeros(len(x) + (len(x)-1)*(nz))
z[::nz+1] = x
print(z)

[1. 0. 0. ... 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [195]:
x1= np.ones((5,5,3))
x2= 2*np.ones((5,5))
print(x1 * x2[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [196]:
A = np.arange(16).reshape(4,4)
A[[0,1]] = A[[1,0]]
print(A)

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [197]:
faces = np.random.randint(0,10,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[(0, 1) (0, 2) (0, 3) ... (7, 9) (8, 9) (9, 9)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [199]:
C = np.bincount([2,1,3,1,2,1])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 1 2 2 3]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [202]:
x = np.arange(10)
n=3
ret = np.cumsum(x,dtype=float)
ret[n:] = ret[n:] - ret[:-n]
print(ret[n - 1:] / n)

[1. 2. 3. ... 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [205]:
x= np.random.randint(0,1,10)
print(np.logical_not(x, out=x))

x = np.random.uniform(-1.0,1.0,10)
print(np.negative(x, out=x))

[1 1 1 ... 1 1 1]
[ 0.19722608  0.78674366 -0.8281157  ... -0.99285286  0.59964144
  0.01782105]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [211]:
P0 = np.random.uniform(0,10,(3,2))
P1 = np.random.uniform(0,10,(3,2))
p = np.random.uniform(0,10,(3,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[1.21655232 2.00756659 4.38936   ]
 [2.57553545 4.10717935 5.49884747]
 [2.01408997 2.43117199 3.77956916]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [213]:
x = np.arange(1,15,dtype=np.uint32)
R = np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 0 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 ...
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [215]:
x= np.random.uniform(0,1,(4,4))
U, S, V = np.linalg.svd(x)
rank = np.sum(S > 1e-10)
print(rank)

x= np.random.uniform(0,1,(2,3))
U, S, V = np.linalg.svd(x)
rank = np.sum(S > 1e-10)
print(rank)

4
2


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [216]:
x = np.random.randint(0,20,100)
print(np.bincount(x).argmax())

7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [217]:
x = np.random.randint(0,3,(10,10))
n = 3
i = 1 + (x.shape[0]-3)
j = 1 + (x.shape[1]-3)
C = np.lib.stride_tricks.as_strided(x, shape=(i, j, n, n), strides=x.strides + x.strides)
print(C)

[[[[0 1 0]
   [1 2 0]
   [2 1 1]]

  [[1 0 2]
   [2 0 1]
   [1 1 2]]

  [[0 2 0]
   [0 1 2]
   [1 2 2]]

  ...

  [[1 0 0]
   [0 2 2]
   [0 1 0]]

  [[0 0 2]
   [2 2 0]
   [1 0 2]]

  [[0 2 0]
   [2 0 1]
   [0 2 2]]]


 [[[1 2 0]
   [2 1 1]
   [2 1 2]]

  [[2 0 1]
   [1 1 2]
   [1 2 1]]

  [[0 1 2]
   [1 2 2]
   [2 1 2]]

  ...

  [[0 2 2]
   [0 1 0]
   [0 0 2]]

  [[2 2 0]
   [1 0 2]
   [0 2 0]]

  [[2 0 1]
   [0 2 2]
   [2 0 0]]]


 [[[2 1 1]
   [2 1 2]
   [0 1 0]]

  [[1 1 2]
   [1 2 1]
   [1 0 0]]

  [[1 2 2]
   [2 1 2]
   [0 0 0]]

  ...

  [[0 1 0]
   [0 0 2]
   [2 0 1]]

  [[1 0 2]
   [0 2 0]
   [0 1 0]]

  [[0 2 2]
   [2 0 0]
   [1 0 2]]]


 ...


 [[[0 1 2]
   [1 1 0]
   [1 2 2]]

  [[1 2 0]
   [1 0 1]
   [2 2 1]]

  [[2 0 2]
   [0 1 2]
   [2 1 0]]

  ...

  [[0 2 0]
   [2 2 2]
   [2 2 2]]

  [[2 0 2]
   [2 2 1]
   [2 2 1]]

  [[0 2 1]
   [2 1 0]
   [2 1 0]]]


 [[[1 1 0]
   [1 2 2]
   [2 0 2]]

  [[1 0 1]
   [2 2 1]
   [0 2 1]]

  [[0 1 2]
   [2 1 0]
   [2 1 1]]

  ...

  [[2

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [218]:
p, n = 5, 10
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[50.]
 [50.]
 [50.]
 ...
 [50.]
 [50.]
 [50.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [219]:
x = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], k), axis=0),
                                       np.arange(0, x.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [221]:
Z = np.arange(500)
np.random.shuffle(Z)
n = 10
print (Z[np.argsort(Z)[-n]])

490


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [225]:
x = np.array([("mumbai", 27.5, 2),
              ("chennai", 35.6, 1)])
R = np.core.records.fromarrays(x.T, 
                               names='City, Temp, rank',
                               formats = 'S8, f8, i8')
print(R)

[(b'mumbai', 27.5, 2) (b'chennai', 35.6, 1)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [227]:
x1= np.random.uniform(0,1,10)
x2= np.random.uniform(0,1,10)

np.einsum('i->', x1)
np.einsum('i,i->i',x1,x2)
np.einsum('i,i', x1,x2)
np.einsum('i,j->ij',x1,x2)

array([[0.10619159, 0.15426807, 0.06854411, ..., 0.12876494, 0.14896096,
        0.09037745],
       [0.2555195 , 0.37120172, 0.16493168, ..., 0.30983576, 0.35843169,
        0.21746733],
       [0.34276368, 0.49794426, 0.2212457 , ..., 0.4156256 , 0.48081404,
        0.29171904],
       ...,
       [0.22572948, 0.32792476, 0.14570294, ..., 0.27371322, 0.31664354,
        0.19211366],
       [0.23170675, 0.33660814, 0.14956113, ..., 0.28096109, 0.32502819,
        0.1972008 ],
       [0.2537356 , 0.36861019, 0.16378022, ..., 0.30767265, 0.35592931,
        0.21594909]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)